/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      'Users',
      [
        {
          name: 'Вторресурс',
          email: 'ooovtorresurs@yandex.ru',
          password: '12345',
          idRole: 1,
          rating: 3,
          phoneNumber: '88002007173',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Завод РЕЦИКЛ',
          email: 'company@zavrecycle.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '88127666685',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Экотранс',
          email: 'office@spb-ecotrans.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '89013252501',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Юнэп',
          email: '01@unepspb.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '78124182363',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Экологические цифры',
          email: 'info@othodopasen.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '89119254951',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Природоохранный центр-Групп',
          email: 'spb@pc-corp.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '88123244107',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Синергия ',
          email: 'rve@asd.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '89215129348',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Тэкон',
          email: 'info@zavodtekon.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '88005504492',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Промышленная Экология',
          email: 'info@promecology.spb.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '78124545627',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Экострой',
          email: 'info@ecospb.com',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '78123288069',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Эколог',
          email: 'iSpb-ecolog@yandex.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '89062551690',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Эко Серви',
          email: 'market@ecoservice-spb.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '89217752588',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'АвтоСПэк',
          email: '9030337@mail.ru',
          password: '12345',
          idRole: 1,
          rating: 4,
          phoneNumber: '88129030337',
          avatar: 'nety',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    )
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Users', null, {})
  },
}
